[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.0"
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
loyal-inference = "56wz9nvWpZE9t4GawPCMC7gHCaJKz53WsCWrasSCbiBJ"
loyal-oracle = "9Sg7UG96gVEPChRdT5Y6DKeaiMV5eTYm1phsWArna98t"

[programs.localnet]
loyal-inference = "56wz9nvWpZE9t4GawPCMC7gHCaJKz53WsCWrasSCbiBJ"
loyal-oracle = "9Sg7UG96gVEPChRdT5Y6DKeaiMV5eTYm1phsWArna98t"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/fixtures/metadata.so"
upgradeable = false

[[test.genesis]]
address = "DELeGGvXpWV2fqJUhqcF5ZSYMS4JTLjteaAMARRSaeSh"
program = "tests/fixtures/dlp.so"
upgradeable = false

[[test.genesis]]
address = "BTWAqWNBmF2TboMh3fxMJfgR16xGHYD7Kgr2dPwbRPBi"
program = "tests/fixtures/permission.so"
upgradeable = false