[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.0"
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
loyal-agent = "7JD7sixsC9bAbCttL1MxbrfNauXjVsAZciGzuicivons"
loyal-inference = "3ezv3YP5V83UP6KNqgHgt7NGE6JonkSK32nnbMyFEX4U"
loyal-oracle = "9Sg7UG96gVEPChRdT5Y6DKeaiMV5eTYm1phsWArna98t"

[programs.localnet]
loyal-inference = "3ezv3YP5V83UP6KNqgHgt7NGE6JonkSK32nnbMyFEX4U"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
